let users know which themes are available
This also means users get a standard error message if they use a theme
that doesn't exist:

    -> bin/cake bake controller posts --theme asdf
	Error: "asdf" is not a valid value for --theme.
		Please use one of ...